# Generated by Django 4.0.4 on 2023-09-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailevent',
            name='folder',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
