# Generated by Django 4.0.4 on 2023-09-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_city_user_country_user_hash_user_hash_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_uuid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
