# Generated by Django 4.0.4 on 2023-09-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_user_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_uuid',
        ),
    ]
